class ConfigurationError(Exception): ...
class ConfigurationValidationError(ConfigurationError): ...
class ConfigurationImportError(ConfigurationError): ...
class ConfigurationExportError(ConfigurationError): ...
