SCHEMA_VERSION=12
SCHEMA_SQL=r'''
CREATE TABLE IF NOT EXISTS schema_metadata (schema_version INTEGER NOT NULL, applied_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS event_identity (event_id TEXT PRIMARY KEY,event_type TEXT NOT NULL,request_id TEXT NOT NULL UNIQUE,occurred_at TEXT NOT NULL,committed_at TEXT NOT NULL,payload_json TEXT NOT NULL,payload_sha256 TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS audit_history (audit_id INTEGER PRIMARY KEY AUTOINCREMENT,event_id TEXT NOT NULL,service_name TEXT NOT NULL,action_name TEXT NOT NULL,recorded_at TEXT NOT NULL,detail_json TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS assets (asset_id TEXT PRIMARY KEY,asset_name TEXT NOT NULL,asset_type TEXT NOT NULL,state TEXT NOT NULL CHECK(state IN ('PLANNED','IN PROGRESS','COMPLETED','CANCELLED','REVIEW')),created_event_id TEXT NOT NULL,created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS inventory_authority (asset_id TEXT PRIMARY KEY,quantity INTEGER NOT NULL CHECK(quantity>=0),total_cost_minor INTEGER NOT NULL CHECK(total_cost_minor>=0),last_event_id TEXT NOT NULL,verified_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS inventory_history (history_id INTEGER PRIMARY KEY AUTOINCREMENT,event_id TEXT NOT NULL,asset_id TEXT NOT NULL,quantity_delta INTEGER NOT NULL,cost_delta_minor INTEGER NOT NULL,resulting_quantity INTEGER NOT NULL CHECK(resulting_quantity>=0),resulting_total_cost_minor INTEGER NOT NULL CHECK(resulting_total_cost_minor>=0),recorded_at TEXT NOT NULL,UNIQUE(event_id,asset_id));
CREATE TABLE IF NOT EXISTS inventory_movements (movement_id TEXT PRIMARY KEY,asset_id TEXT NOT NULL,event_id TEXT NOT NULL,quantity_delta INTEGER NOT NULL,cost_delta_minor INTEGER NOT NULL,movement_type TEXT NOT NULL,recorded_at TEXT NOT NULL,UNIQUE(event_id,asset_id,movement_type));
CREATE TABLE IF NOT EXISTS inventory_adjustments (adjustment_id TEXT PRIMARY KEY,asset_id TEXT NOT NULL,adjustment_type TEXT NOT NULL CHECK(adjustment_type IN ('DAMAGE','LOSS')),adjustment_quantity INTEGER NOT NULL CHECK(adjustment_quantity>0),evidence_type TEXT NOT NULL,evidence_reference TEXT NOT NULL,evidence_complete INTEGER NOT NULL CHECK(evidence_complete=1),request_id TEXT NOT NULL UNIQUE,replay_key TEXT NOT NULL UNIQUE,movement_id TEXT NOT NULL UNIQUE,event_id TEXT NOT NULL UNIQUE,control_result TEXT NOT NULL CHECK(control_result='CONTROLLED'),committed_at TEXT NOT NULL,verified_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS sales (sale_id TEXT PRIMARY KEY,asset_id TEXT NOT NULL,quantity INTEGER NOT NULL CHECK(quantity>0),revenue_minor INTEGER NOT NULL CHECK(revenue_minor>=0),marketplace_fees_minor INTEGER NOT NULL CHECK(marketplace_fees_minor>=0),shipping_minor INTEGER NOT NULL CHECK(shipping_minor>=0),packaging_minor INTEGER NOT NULL CHECK(packaging_minor>=0),cogs_minor INTEGER NOT NULL CHECK(cogs_minor>=0),profit_minor INTEGER NOT NULL,state TEXT NOT NULL CHECK(state IN ('COMPLETED','REVIEW')),created_event_id TEXT NOT NULL UNIQUE,created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS sales_financial_history (financial_history_id INTEGER PRIMARY KEY AUTOINCREMENT,event_id TEXT NOT NULL UNIQUE,sale_id TEXT NOT NULL,revenue_minor INTEGER NOT NULL,marketplace_fees_minor INTEGER NOT NULL,shipping_minor INTEGER NOT NULL,packaging_minor INTEGER NOT NULL,cogs_minor INTEGER NOT NULL,profit_minor INTEGER NOT NULL,recorded_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS replay_defense_history (replay_history_id INTEGER PRIMARY KEY AUTOINCREMENT,request_id TEXT NOT NULL,original_event_id TEXT NOT NULL,attempted_event_type TEXT NOT NULL,payload_sha256 TEXT NOT NULL,defense_result TEXT NOT NULL CHECK(defense_result='BLOCKED'),recorded_at TEXT NOT NULL,UNIQUE(request_id,attempted_event_type,payload_sha256));
CREATE TABLE IF NOT EXISTS audit_events (audit_event_id INTEGER PRIMARY KEY AUTOINCREMENT,event_id TEXT NOT NULL,authority_type TEXT NOT NULL,authority_id TEXT NOT NULL,verification_result TEXT NOT NULL,recorded_at TEXT NOT NULL,UNIQUE(event_id,authority_type,authority_id));
CREATE TABLE IF NOT EXISTS marketplace_allocations (allocation_id TEXT PRIMARY KEY,asset_id TEXT NOT NULL,marketplace TEXT NOT NULL,allocated_quantity INTEGER NOT NULL CHECK(allocated_quantity>0),state TEXT NOT NULL CHECK(state IN ('ACTIVE','RELEASED')),publication_reference TEXT,event_id TEXT NOT NULL UNIQUE,created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS marketplace_publication_allocations (allocation_id TEXT PRIMARY KEY,asset_id TEXT NOT NULL,marketplace TEXT NOT NULL,publication_reference TEXT NOT NULL,publication_identity TEXT NOT NULL,requested_quantity INTEGER NOT NULL CHECK(requested_quantity>0),allocated_quantity INTEGER NOT NULL CHECK(allocated_quantity>0),released_quantity INTEGER NOT NULL DEFAULT 0,cancelled_quantity INTEGER NOT NULL DEFAULT 0,consumed_quantity INTEGER NOT NULL DEFAULT 0,state TEXT NOT NULL CHECK(state IN ('ACTIVE','RELEASED','CANCELLED','CONSUMED')),source_event_id TEXT NOT NULL,created_at TEXT NOT NULL,committed_at TEXT NOT NULL,verified_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS publication_lifecycle_events (lifecycle_id TEXT PRIMARY KEY,allocation_id TEXT NOT NULL,event_type TEXT NOT NULL CHECK(event_type IN ('LISTED','RELEASE','CANCELLATION','SOLD_CONVERSION')),quantity INTEGER NOT NULL CHECK(quantity>=0),evidence_type TEXT NOT NULL,evidence_reference TEXT NOT NULL,evidence_complete INTEGER NOT NULL CHECK(evidence_complete=1),marketplace TEXT NOT NULL,publication_reference TEXT,publication_identity TEXT,sale_id TEXT,sale_event_id TEXT,source_event_id TEXT,event_id TEXT NOT NULL UNIQUE,request_id TEXT NOT NULL UNIQUE,replay_key TEXT NOT NULL UNIQUE,created_at TEXT NOT NULL,committed_at TEXT NOT NULL,verified_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS exception_authority (exception_id TEXT PRIMARY KEY,source_event_id TEXT,exception_type TEXT NOT NULL,evidence TEXT NOT NULL,state TEXT NOT NULL CHECK(state IN ('REVIEW','COMPLETED')),event_id TEXT NOT NULL UNIQUE,created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS inventory_reconciliations (reconciliation_id TEXT PRIMARY KEY,asset_id TEXT NOT NULL,event_id TEXT NOT NULL UNIQUE,request_id TEXT NOT NULL UNIQUE,replay_key TEXT NOT NULL UNIQUE,evidence_type TEXT NOT NULL,evidence_reference TEXT NOT NULL,evidence_complete INTEGER NOT NULL CHECK(evidence_complete=1),observed_quantity INTEGER NOT NULL CHECK(observed_quantity>=0),remaining_quantity_truth INTEGER NOT NULL CHECK(remaining_quantity_truth>=0),pre_reconciliation_quantity INTEGER NOT NULL CHECK(pre_reconciliation_quantity>=0),variance_quantity INTEGER NOT NULL,authorized_delta INTEGER NOT NULL,post_reconciliation_quantity INTEGER NOT NULL CHECK(post_reconciliation_quantity>=0),reconciliation_reason TEXT NOT NULL,reconciliation_state TEXT NOT NULL CHECK(reconciliation_state='RECONCILED'),inventory_history_reference INTEGER NOT NULL,audit_event_id TEXT NOT NULL,created_at TEXT NOT NULL,committed_at TEXT NOT NULL,verified_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS reconciliation_history (history_id INTEGER PRIMARY KEY AUTOINCREMENT,reconciliation_id TEXT NOT NULL,asset_id TEXT NOT NULL,state TEXT NOT NULL CHECK(state IN ('DETECTED','BLOCKED','ELIGIBLE','COMMITTED','VERIFIED','RECONCILED')),event_id TEXT,request_id TEXT,evidence_reference TEXT,remaining_quantity_truth INTEGER NOT NULL,current_quantity INTEGER NOT NULL,observed_quantity INTEGER NOT NULL,variance_quantity INTEGER NOT NULL,authorized_delta INTEGER,control_result TEXT NOT NULL,recorded_at TEXT NOT NULL);
CREATE TRIGGER IF NOT EXISTS inventory_adjustments_no_update BEFORE UPDATE ON inventory_adjustments BEGIN SELECT RAISE(ABORT,'inventory_adjustments is append-only'); END;
CREATE TRIGGER IF NOT EXISTS inventory_adjustments_no_delete BEFORE DELETE ON inventory_adjustments BEGIN SELECT RAISE(ABORT,'inventory_adjustments is append-only'); END;
CREATE TRIGGER IF NOT EXISTS inventory_movements_no_update BEFORE UPDATE ON inventory_movements BEGIN SELECT RAISE(ABORT,'inventory_movements is append-only'); END;
CREATE TRIGGER IF NOT EXISTS inventory_movements_no_delete BEFORE DELETE ON inventory_movements BEGIN SELECT RAISE(ABORT,'inventory_movements is append-only'); END;
CREATE TRIGGER IF NOT EXISTS inventory_reconciliations_no_update BEFORE UPDATE ON inventory_reconciliations BEGIN SELECT RAISE(ABORT,'inventory_reconciliations is append-only'); END;
CREATE TRIGGER IF NOT EXISTS inventory_reconciliations_no_delete BEFORE DELETE ON inventory_reconciliations BEGIN SELECT RAISE(ABORT,'inventory_reconciliations is append-only'); END;
CREATE TRIGGER IF NOT EXISTS reconciliation_history_no_update BEFORE UPDATE ON reconciliation_history BEGIN SELECT RAISE(ABORT,'reconciliation_history is append-only'); END;
CREATE TRIGGER IF NOT EXISTS reconciliation_history_no_delete BEFORE DELETE ON reconciliation_history BEGIN SELECT RAISE(ABORT,'reconciliation_history is append-only'); END;
CREATE TRIGGER IF NOT EXISTS event_identity_no_update BEFORE UPDATE ON event_identity BEGIN SELECT RAISE(ABORT,'event_identity is immutable'); END;
CREATE TRIGGER IF NOT EXISTS event_identity_no_delete BEFORE DELETE ON event_identity BEGIN SELECT RAISE(ABORT,'event_identity is immutable'); END;
CREATE TRIGGER IF NOT EXISTS inventory_history_no_update BEFORE UPDATE ON inventory_history BEGIN SELECT RAISE(ABORT,'inventory_history is append-only'); END;
CREATE TRIGGER IF NOT EXISTS inventory_history_no_delete BEFORE DELETE ON inventory_history BEGIN SELECT RAISE(ABORT,'inventory_history is append-only'); END;
CREATE TRIGGER IF NOT EXISTS publication_lifecycle_events_no_update BEFORE UPDATE ON publication_lifecycle_events BEGIN SELECT RAISE(ABORT,'publication_lifecycle_events is append-only'); END;
CREATE TRIGGER IF NOT EXISTS publication_lifecycle_events_no_delete BEFORE DELETE ON publication_lifecycle_events BEGIN SELECT RAISE(ABORT,'publication_lifecycle_events is append-only'); END;
CREATE TRIGGER IF NOT EXISTS replay_defense_history_no_update BEFORE UPDATE ON replay_defense_history BEGIN SELECT RAISE(ABORT,'replay_defense_history is append-only'); END;
CREATE TRIGGER IF NOT EXISTS replay_defense_history_no_delete BEFORE DELETE ON replay_defense_history BEGIN SELECT RAISE(ABORT,'replay_defense_history is append-only'); END;
CREATE TRIGGER IF NOT EXISTS audit_events_no_update BEFORE UPDATE ON audit_events BEGIN SELECT RAISE(ABORT,'audit_events is append-only'); END;
CREATE TRIGGER IF NOT EXISTS audit_events_no_delete BEFORE DELETE ON audit_events BEGIN SELECT RAISE(ABORT,'audit_events is append-only'); END;
'''
