from pathlib import Path
from services.m39a_acceptance_service import M39AAcceptanceService, SETTLEMENT_ID
from services.product_sale_execution_service import SALE_ID
from services.order_closure_service import OrderClosureService

CLOSURE_ID='CLOSURE-M39B-001'; CLOSURE_REQUEST_ID='M39B-ORDER-CLOSE-REQUEST-001'

class M39BAcceptanceService:
    def __init__(self,path): self.path=Path(path); self.closure=OrderClosureService(self.path)
    def _lineage(self):
        r=M39AAcceptanceService(self.path).execute()
        if r['passed']!=12: raise RuntimeError('M39A accepted SETTLED authority incomplete')
        with self.closure.database.read_connection() as c:
            sale=c.execute('SELECT * FROM sales WHERE sale_id=?',(SALE_ID,)).fetchone(); sold=c.execute("SELECT * FROM publication_lifecycle_events WHERE sale_id=? AND event_type='SOLD_CONVERSION'",(SALE_ID,)).fetchone(); alloc=c.execute('SELECT * FROM marketplace_publication_allocations WHERE allocation_id=?',(sold['allocation_id'],)).fetchone(); listing=c.execute('SELECT * FROM marketplace_listing_identities WHERE listing_identity_id=?',(alloc['publication_identity'],)).fetchone(); link=c.execute("SELECT * FROM inventory_product_links WHERE asset_id=? AND product_id=? AND state='LINKED'",(sale['asset_id'],listing['product_id'])).fetchone()
        return dict(product_id=listing['product_id'],asset_id=sale['asset_id'],listing_id=listing['listing_identity_id'],allocation_id=alloc['allocation_id'],marketplace=sold['marketplace'])
    def execute(self):
        lineage=self._lineage(); k=dict(closure_id=CLOSURE_ID,sale_id=SALE_ID,settlement_id=SETTLEMENT_ID,closure_request_id=CLOSURE_REQUEST_ID,intent='CLOSE',**lineage)
        self.closure.close(**k); self.closure.close(**k); self.closure=OrderClosureService(self.path); self.closure.close(**k); return self.verify()
    def verify(self):
        with self.closure.database.read_connection() as c:
            sale=c.execute('SELECT * FROM sales WHERE sale_id=?',(SALE_ID,)).fetchone(); settlement=c.execute('SELECT * FROM settlement_executions WHERE settlement_id=?',(SETTLEMENT_ID,)).fetchone(); closure=c.execute('SELECT * FROM order_closures WHERE closure_id=?',(CLOSURE_ID,)).fetchone(); history=c.execute('SELECT COUNT(*) n FROM order_closure_history WHERE closure_id=?',(CLOSURE_ID,)).fetchone()['n']; replay=c.execute("SELECT COUNT(*) n FROM replay_defense_history WHERE request_id=? AND attempted_event_type='ORDER_CLOSE'",(CLOSURE_REQUEST_ID,)).fetchone()['n']; sales=c.execute('SELECT COUNT(*) n FROM sales WHERE sale_id=?',(SALE_ID,)).fetchone()['n']; fin=c.execute('SELECT COUNT(*) n FROM sales_financial_history WHERE sale_id=?',(SALE_ID,)).fetchone()['n']; settlements=c.execute('SELECT COUNT(*) n FROM settlement_executions WHERE sale_id=?',(SALE_ID,)).fetchone()['n']; sold=c.execute("SELECT COUNT(*) n FROM publication_lifecycle_events WHERE sale_id=? AND event_type='SOLD_CONVERSION'",(SALE_ID,)).fetchone()['n']; invmoves=0 if not closure else c.execute('SELECT COUNT(*) n FROM inventory_history WHERE event_id=?',(closure['closure_event_id'],)).fetchone()['n']; audit=0 if not closure else c.execute("SELECT COUNT(*) n FROM audit_events WHERE event_id=? AND authority_type='ORDER_CLOSE' AND authority_id=? AND verification_result='VERIFIED'",(closure['closure_event_id'],CLOSURE_ID)).fetchone()['n']; event=0 if not closure else c.execute("SELECT COUNT(*) n FROM event_identity WHERE event_id=? AND event_type='ORDER_CLOSE'",(closure['closure_event_id'],)).fetchone()['n']
        checks=[('Accepted M39A SETTLED authority',bool(settlement and settlement['settlement_result']=='SETTLED'),'SETTLED'),('Authoritative product-aware sale identity',bool(sale and closure and closure['sale_id']==SALE_ID),SALE_ID),('Product → asset lineage',bool(closure and closure['product_id'] and closure['asset_id']),'VERIFIED'),('Listing → allocation lineage',bool(closure and closure['listing_id'] and closure['allocation_id']),'VERIFIED'),('Marketplace lineage match',bool(closure and settlement and closure['marketplace']==settlement['settlement_platform']),'eBay = eBay'),('Explicit closure request + event identity',event==1,CLOSURE_REQUEST_ID),('Standalone order closure execution',bool(closure and closure['closure_result']=='CLOSED'),'CLOSED'),('Exactly-once order closure',history==1,'1 closure / 1 history'),('ZERO inventory mutation',invmoves==0,'ZERO'),('ZERO second sale + financial + settlement',sales==1 and fin==1 and settlements==1,'1 / 1 / 1'),('ZERO second SOLD conversion + audit explainability',sold==1 and audit==1,'1 SOLD / VERIFIED audit'),('Persistent replay + restart reconstruction',replay==1 and history==1,'PASS / PASS')]; passed=sum(ok for _,ok,_ in checks)
        return {'checks':checks,'passed':passed,'settlement':'SETTLED' if settlement else 'BLOCKED','lineage':'VERIFIED' if all(x[1] for x in checks[1:5]) else 'BLOCKED','closure':'CLOSED' if closure else 'BLOCKED','inventory':'ZERO' if invmoves==0 else 'MUTATED','second_sale':'NO' if sales==1 else 'YES','second_financial':'NO' if fin==1 else 'YES','second_settlement':'NO' if settlements==1 else 'YES','second_sold':'NO' if sold==1 else 'YES','history':'APPEND-ONLY' if history==1 else 'BLOCKED','replay':'PASS' if replay==1 else 'FAIL','restart':'PASS' if replay==1 and history==1 else 'FAIL','result':'PRODUCT-AWARE SETTLEMENT + ORDER CLOSURE VERIFIED' if passed==12 else 'BLOCKED'}
