from pathlib import Path
from services.m39b_acceptance_service import M39BAcceptanceService,CLOSURE_ID
from services.m39a_acceptance_service import SETTLEMENT_ID
from services.product_sale_execution_service import SALE_ID
from services.financial_finalization_service import FinancialFinalizationService
FINALIZATION_ID='FINALIZATION-M40A-001'; FINALIZATION_REQUEST_ID='M40A-FINALIZE-REQUEST-001'
class M40AAcceptanceService:
 def __init__(self,path): self.path=Path(path); self.finalization=FinancialFinalizationService(self.path)
 def execute(self):
  if M39BAcceptanceService(self.path).execute()['passed']!=12: raise RuntimeError('M39B CLOSED authority incomplete')
  k=dict(finalization_id=FINALIZATION_ID,closure_id=CLOSURE_ID,sale_id=SALE_ID,settlement_id=SETTLEMENT_ID,finalization_request_id=FINALIZATION_REQUEST_ID,intent='FINALIZE'); self.finalization.finalize(**k); self.finalization.finalize(**k); self.finalization=FinancialFinalizationService(self.path); self.finalization.finalize(**k); return self.verify()
 def verify(self):
  with self.finalization.database.read_connection() as c:
   f=c.execute('SELECT * FROM financial_finalizations WHERE finalization_id=?',(FINALIZATION_ID,)).fetchone(); h=c.execute('SELECT COUNT(*) n FROM financial_finalization_history WHERE finalization_id=?',(FINALIZATION_ID,)).fetchone()['n']; closure=c.execute('SELECT * FROM order_closures WHERE closure_id=?',(CLOSURE_ID,)).fetchone(); settlement=c.execute('SELECT * FROM settlement_executions WHERE settlement_id=?',(SETTLEMENT_ID,)).fetchone(); financial=c.execute('SELECT * FROM sales_financial_history WHERE sale_id=?',(SALE_ID,)).fetchall(); sales=c.execute('SELECT COUNT(*) n FROM sales WHERE sale_id=?',(SALE_ID,)).fetchone()['n']; settlements=c.execute('SELECT COUNT(*) n FROM settlement_executions WHERE sale_id=?',(SALE_ID,)).fetchone()['n']; closures=c.execute('SELECT COUNT(*) n FROM order_closures WHERE sale_id=?',(SALE_ID,)).fetchone()['n']; sold=c.execute("SELECT COUNT(*) n FROM publication_lifecycle_events WHERE sale_id=? AND event_type='SOLD_CONVERSION'",(SALE_ID,)).fetchone()['n']; replay=c.execute("SELECT COUNT(*) n FROM replay_defense_history WHERE request_id=? AND attempted_event_type='FINANCIAL_FINALIZATION'",(FINALIZATION_REQUEST_ID,)).fetchone()['n']; invmoves=0 if not f else c.execute('SELECT COUNT(*) n FROM inventory_history WHERE event_id=?',(f['finalization_event_id'],)).fetchone()['n']; audit=0 if not f else c.execute("SELECT COUNT(*) n FROM audit_events WHERE event_id=? AND authority_type='FINANCIAL_FINALIZATION' AND authority_id=? AND verification_result='VERIFIED'",(f['finalization_event_id'],FINALIZATION_ID)).fetchone()['n']; event=0 if not f else c.execute("SELECT COUNT(*) n FROM event_identity WHERE event_id=? AND event_type='FINANCIAL_FINALIZATION'",(f['finalization_event_id'],)).fetchone()['n']
  expected=None if len(financial)!=1 else int(financial[0]['revenue_minor'])-int(financial[0]['marketplace_fees_minor'])-int(financial[0]['shipping_minor'])-int(financial[0]['packaging_minor'])
  checks=[('Accepted CLOSED order authority',bool(closure and closure['closure_result']=='CLOSED'),'CLOSED'),('Authoritative sale + M24 financial lineage',sales==1 and len(financial)==1,'1 sale / 1 M24 financial'),('Accepted SETTLED lineage',bool(settlement and settlement['settlement_result']=='SETTLED'),'SETTLED'),('Expected net proceeds reconstruction',expected is not None and expected==settlement['observed_payout_minor'],expected),('Explicit finalization request + event identity',event==1,FINALIZATION_REQUEST_ID),('Standalone financial finalization execution',bool(f and f['finalization_result']=='FINALIZED'),'FINALIZED'),('Exactly-once FINALIZED authority',h==1,'1 finalization / 1 history'),('ZERO inventory mutation',invmoves==0,'ZERO'),('ZERO second sale + M24 financial event',sales==1 and len(financial)==1,'1 / 1'),('ZERO second settlement + order closure',settlements==1 and closures==1,'1 / 1'),('ZERO second SOLD conversion + audit explainability',sold==1 and audit==1,'1 SOLD / VERIFIED audit'),('Persistent replay + restart reconstruction',replay==1 and h==1,'PASS / PASS')]; passed=sum(ok for _,ok,_ in checks)
  return {'checks':checks,'passed':passed,'closure':'CLOSED' if closure else 'BLOCKED','financial':'VERIFIED' if len(financial)==1 else 'BLOCKED','settlement':'SETTLED' if settlement else 'BLOCKED','finalization':'FINALIZED' if f else 'BLOCKED','inventory':'ZERO' if invmoves==0 else 'MUTATED','second_sale':'NO' if sales==1 else 'YES','second_financial':'NO' if len(financial)==1 else 'YES','second_settlement':'NO' if settlements==1 else 'YES','second_closure':'NO' if closures==1 else 'YES','second_sold':'NO' if sold==1 else 'YES','history':'APPEND-ONLY' if h==1 else 'BLOCKED','replay':'PASS' if replay==1 else 'FAIL','restart':'PASS' if replay==1 and h==1 else 'FAIL','result':'CLOSED ORDER FINANCIAL FINALIZATION VERIFIED' if passed==12 else 'BLOCKED'}
