from pathlib import Path
from services.m40a_acceptance_service import M40AAcceptanceService,FINALIZATION_ID
from services.product_sale_execution_service import SALE_ID
from services.profit_recognition_service import ProfitRecognitionService
RECOGNITION_ID='RECOGNITION-M40B-001'; RECOGNITION_REQUEST_ID='M40B-RECOGNIZE-REQUEST-001'
class M40BAcceptanceService:
 def __init__(self,path): self.path=Path(path); self.recognition=ProfitRecognitionService(self.path)
 def execute(self):
  if M40AAcceptanceService(self.path).execute()['passed']!=12: raise RuntimeError('M40A FINALIZED authority incomplete')
  k=dict(recognition_id=RECOGNITION_ID,finalization_id=FINALIZATION_ID,sale_id=SALE_ID,recognition_request_id=RECOGNITION_REQUEST_ID,intent='RECOGNIZE'); self.recognition.recognize(**k); self.recognition.recognize(**k); self.recognition=ProfitRecognitionService(self.path); self.recognition.recognize(**k); return self.verify()
 def verify(self):
  with self.recognition.database.read_connection() as c:
   r=c.execute('SELECT * FROM profit_recognitions WHERE recognition_id=?',(RECOGNITION_ID,)).fetchone(); f=c.execute('SELECT * FROM financial_finalizations WHERE finalization_id=?',(FINALIZATION_ID,)).fetchone(); h=c.execute('SELECT COUNT(*) n FROM profit_recognition_history WHERE recognition_id=?',(RECOGNITION_ID,)).fetchone()['n']; replay=c.execute("SELECT COUNT(*) n FROM replay_defense_history WHERE request_id=? AND attempted_event_type='PROFIT_RECOGNITION'",(RECOGNITION_REQUEST_ID,)).fetchone()['n']; counts={t:c.execute(f'SELECT COUNT(*) n FROM {t}').fetchone()['n'] for t in ('sales','sales_financial_history','settlement_executions','order_closures','financial_finalizations')}; sold=c.execute("SELECT COUNT(*) n FROM publication_lifecycle_events WHERE event_type='SOLD_CONVERSION'").fetchone()['n']; invmoves=0 if not r else c.execute('SELECT COUNT(*) n FROM inventory_history WHERE event_id=?',(r['recognition_event_id'],)).fetchone()['n']; audit=0 if not r else c.execute("SELECT COUNT(*) n FROM audit_events WHERE event_id=? AND authority_type='PROFIT_RECOGNITION' AND authority_id=? AND verification_result='VERIFIED'",(r['recognition_event_id'],RECOGNITION_ID)).fetchone()['n']; event=0 if not r else c.execute("SELECT COUNT(*) n FROM event_identity WHERE event_id=? AND event_type='PROFIT_RECOGNITION'",(r['recognition_event_id'],)).fetchone()['n']
  truth=bool(r and f and int(r['recognized_profit_minor'])==int(f['profit_minor']) and int(r['recognized_revenue_minor'])==int(f['revenue_minor']) and int(r['recognized_cogs_minor'])==int(f['cogs_minor']))
  checks=[('Accepted FINALIZED authority',bool(f and f['finalization_result']=='FINALIZED'),'FINALIZED'),('Finalized sale financial truth reconstruction',truth,'revenue / COGS / profit match'),('Recognized profit authority',truth,r['recognized_profit_minor'] if r else None),('Explicit recognition request + event identity',event==1,RECOGNITION_REQUEST_ID),('Standalone profit recognition execution',bool(r and r['recognition_result']=='PROFIT_RECOGNIZED'),'PROFIT_RECOGNIZED'),('Exactly-once recognized profit authority',h==1,'1 recognition / 1 history'),('ZERO inventory mutation',invmoves==0,'ZERO'),('ZERO second sale + M24 financial event',counts['sales']==1 and counts['sales_financial_history']==1,'1 / 1'),('ZERO second settlement + order closure',counts['settlement_executions']==1 and counts['order_closures']==1,'1 / 1'),('ZERO second financial finalization',counts['financial_finalizations']==1,'1 FINALIZED'),('ZERO second SOLD conversion + audit explainability',sold==1 and audit==1,'1 SOLD / VERIFIED audit'),('Persistent replay + restart reconstruction',replay==1 and h==1,'PASS / PASS')]; passed=sum(ok for _,ok,_ in checks)
  return {'checks':checks,'passed':passed,'finalization':'FINALIZED' if f else 'BLOCKED','profit':'PROFIT_RECOGNIZED' if r else 'BLOCKED','recognized_profit':None if not r else r['recognized_profit_minor'],'inventory':'ZERO' if invmoves==0 else 'MUTATED','second_sale':'NO' if counts['sales']==1 else 'YES','second_financial':'NO' if counts['sales_financial_history']==1 else 'YES','second_settlement':'NO' if counts['settlement_executions']==1 else 'YES','second_closure':'NO' if counts['order_closures']==1 else 'YES','second_finalization':'NO' if counts['financial_finalizations']==1 else 'YES','second_sold':'NO' if sold==1 else 'YES','history':'APPEND-ONLY' if h==1 else 'BLOCKED','replay':'PASS' if replay==1 else 'FAIL','restart':'PASS' if replay==1 and h==1 else 'FAIL','result':'FINALIZED SALE PROFIT RECOGNITION VERIFIED' if passed==12 else 'BLOCKED'}
