from pathlib import Path
from services.m40b_acceptance_service import M40BAcceptanceService,RECOGNITION_ID
from services.product_sale_execution_service import SALE_ID
from services.business_ledger_posting_service import BusinessLedgerPostingService
POSTING_ID='POSTING-M41A-001'; POSTING_REQUEST_ID='M41A-POST-REQUEST-001'; LEDGER_ACCOUNT='REALIZED_SALES_PROFIT'
class M41AAcceptanceService:
 def __init__(self,path): self.path=Path(path); self.posting=BusinessLedgerPostingService(self.path)
 def execute(self):
  if M40BAcceptanceService(self.path).execute()['passed']!=12: raise RuntimeError('M40B PROFIT_RECOGNIZED authority incomplete')
  k=dict(posting_id=POSTING_ID,recognition_id=RECOGNITION_ID,sale_id=SALE_ID,posting_request_id=POSTING_REQUEST_ID,ledger_account=LEDGER_ACCOUNT,intent='POST'); self.posting.post(**k); self.posting.post(**k); self.posting=BusinessLedgerPostingService(self.path); self.posting.post(**k); return self.verify()
 def verify(self):
  with self.posting.database.read_connection() as c:
   p=c.execute('SELECT * FROM business_ledger_postings WHERE posting_id=?',(POSTING_ID,)).fetchone(); r=c.execute('SELECT * FROM profit_recognitions WHERE recognition_id=?',(RECOGNITION_ID,)).fetchone(); h=c.execute('SELECT COUNT(*) n FROM business_ledger_history WHERE posting_id=?',(POSTING_ID,)).fetchone()['n']; replay=c.execute("SELECT COUNT(*) n FROM replay_defense_history WHERE request_id=? AND attempted_event_type='BUSINESS_LEDGER_POSTING'",(POSTING_REQUEST_ID,)).fetchone()['n']; counts={t:c.execute(f'SELECT COUNT(*) n FROM {t}').fetchone()['n'] for t in ('sales','sales_financial_history','settlement_executions','order_closures','financial_finalizations','profit_recognitions')}; sold=c.execute("SELECT COUNT(*) n FROM publication_lifecycle_events WHERE event_type='SOLD_CONVERSION'").fetchone()['n']; invmoves=0 if not p else c.execute('SELECT COUNT(*) n FROM inventory_history WHERE event_id=?',(p['posting_event_id'],)).fetchone()['n']; audit=0 if not p else c.execute("SELECT COUNT(*) n FROM audit_events WHERE event_id=? AND authority_type='BUSINESS_LEDGER_POSTING' AND authority_id=? AND verification_result='VERIFIED'",(p['posting_event_id'],POSTING_ID)).fetchone()['n']; event=0 if not p else c.execute("SELECT COUNT(*) n FROM event_identity WHERE event_id=? AND event_type='BUSINESS_LEDGER_POSTING'",(p['posting_event_id'],)).fetchone()['n']
  truth=bool(p and r and int(p['posted_revenue_minor'])==int(r['recognized_revenue_minor']) and int(p['posted_cogs_minor'])==int(r['recognized_cogs_minor']) and int(p['posted_profit_minor'])==int(r['recognized_profit_minor']))
  checks=[('Accepted PROFIT_RECOGNIZED authority',bool(r and r['recognition_result']=='PROFIT_RECOGNIZED'),'PROFIT_RECOGNIZED'),('Recognized profit truth reconstruction',truth,'revenue / COGS / profit match'),('Business ledger account authority',bool(p and p['ledger_account']==LEDGER_ACCOUNT),LEDGER_ACCOUNT),('Explicit posting request + event identity',event==1,POSTING_REQUEST_ID),('Standalone business ledger posting execution',bool(p and p['posting_result']=='POSTED'),'POSTED'),('Exactly-once POSTED authority',h==1,'1 posting / 1 history'),('ZERO inventory mutation',invmoves==0,'ZERO'),('ZERO second sale + M24 financial event',counts['sales']==1 and counts['sales_financial_history']==1,'1 / 1'),('ZERO second settlement + order closure',counts['settlement_executions']==1 and counts['order_closures']==1,'1 / 1'),('ZERO second finalization + profit recognition',counts['financial_finalizations']==1 and counts['profit_recognitions']==1,'1 / 1'),('ZERO second SOLD conversion + audit explainability',sold==1 and audit==1,'1 SOLD / VERIFIED audit'),('Persistent replay + restart reconstruction',replay==1 and h==1,'PASS / PASS')]; passed=sum(ok for _,ok,_ in checks)
  return {'checks':checks,'passed':passed,'recognition':'PROFIT_RECOGNIZED' if r else 'BLOCKED','posting':'POSTED' if p else 'BLOCKED','posted_profit':None if not p else p['posted_profit_minor'],'account':None if not p else p['ledger_account'],'inventory':'ZERO' if invmoves==0 else 'MUTATED','second_sale':'NO' if counts['sales']==1 else 'YES','second_financial':'NO' if counts['sales_financial_history']==1 else 'YES','second_settlement':'NO' if counts['settlement_executions']==1 else 'YES','second_closure':'NO' if counts['order_closures']==1 else 'YES','second_finalization':'NO' if counts['financial_finalizations']==1 else 'YES','second_recognition':'NO' if counts['profit_recognitions']==1 else 'YES','second_sold':'NO' if sold==1 else 'YES','history':'APPEND-ONLY' if h==1 else 'BLOCKED','replay':'PASS' if replay==1 else 'FAIL','restart':'PASS' if replay==1 and h==1 else 'FAIL','result':'RECOGNIZED PROFIT BUSINESS LEDGER POSTING VERIFIED' if passed==12 else 'BLOCKED'}
