from pathlib import Path
from services.m41a_acceptance_service import M41AAcceptanceService,POSTING_ID,LEDGER_ACCOUNT
from services.business_ledger_balance_service import BusinessLedgerBalanceService
BALANCE_ID='BALANCE-M41B-001'; BALANCE_REQUEST_ID='M41B-BALANCE-REQUEST-001'
class M41BAcceptanceService:
 def __init__(self,path): self.path=Path(path); self.balance_service=BusinessLedgerBalanceService(self.path)
 def execute(self):
  if M41AAcceptanceService(self.path).execute()['passed']!=12: raise RuntimeError('M41A POSTED authority incomplete')
  k=dict(balance_id=BALANCE_ID,posting_id=POSTING_ID,balance_request_id=BALANCE_REQUEST_ID,ledger_account=LEDGER_ACCOUNT,intent='BALANCE'); self.balance_service.balance(**k); self.balance_service.balance(**k); self.balance_service=BusinessLedgerBalanceService(self.path); self.balance_service.balance(**k); return self.verify()
 def verify(self):
  with self.balance_service.database.read_connection() as c:
   b=c.execute('SELECT * FROM business_ledger_balances WHERE balance_id=?',(BALANCE_ID,)).fetchone(); p=c.execute('SELECT * FROM business_ledger_postings WHERE posting_id=?',(POSTING_ID,)).fetchone(); h=c.execute('SELECT COUNT(*) n FROM business_ledger_balance_history WHERE balance_id=?',(BALANCE_ID,)).fetchone()['n']; replay=c.execute("SELECT COUNT(*) n FROM replay_defense_history WHERE request_id=? AND attempted_event_type='BUSINESS_LEDGER_BALANCE'",(BALANCE_REQUEST_ID,)).fetchone()['n']; account=c.execute("SELECT COUNT(*) posting_count,COALESCE(SUM(posted_profit_minor),0) profit FROM business_ledger_postings WHERE ledger_account=? AND posting_result='POSTED'",(LEDGER_ACCOUNT,)).fetchone(); counts={t:c.execute(f'SELECT COUNT(*) n FROM {t}').fetchone()['n'] for t in ('sales','sales_financial_history','settlement_executions','order_closures','financial_finalizations','profit_recognitions','business_ledger_postings')}; sold=c.execute("SELECT COUNT(*) n FROM publication_lifecycle_events WHERE event_type='SOLD_CONVERSION'").fetchone()['n']; invmoves=0 if not b else c.execute('SELECT COUNT(*) n FROM inventory_history WHERE event_id=?',(b['balance_event_id'],)).fetchone()['n']; audit=0 if not b else c.execute("SELECT COUNT(*) n FROM audit_events WHERE event_id=? AND authority_type='BUSINESS_LEDGER_BALANCE' AND authority_id=? AND verification_result='VERIFIED'",(b['balance_event_id'],BALANCE_ID)).fetchone()['n']; event=0 if not b else c.execute("SELECT COUNT(*) n FROM event_identity WHERE event_id=? AND event_type='BUSINESS_LEDGER_BALANCE'",(b['balance_event_id'],)).fetchone()['n']
  equation=bool(b and int(b['balanced_profit_minor'])==int(account['profit']) and int(b['posting_count'])==int(account['posting_count'])); truth=bool(b and p and int(b['balanced_profit_minor'])==int(p['posted_profit_minor']) and b['ledger_account']==p['ledger_account'])
  checks=[('Accepted POSTED ledger authority',bool(p and p['posting_result']=='POSTED'),'POSTED'),('Posted ledger truth reconstruction',truth,'posting → account → profit match'),('Ledger posted-profit aggregate authority',equation,'SUM accepted POSTED profit = balance'),('Explicit balance request + event identity',event==1,BALANCE_REQUEST_ID),('Standalone ledger balance execution',bool(b and b['balance_result']=='BALANCED'),'BALANCED'),('Exactly-once BALANCED authority',h==1,'1 balance / 1 history'),('ZERO inventory mutation',invmoves==0,'ZERO'),('ZERO second sale + M24 financial event',counts['sales']==1 and counts['sales_financial_history']==1,'1 / 1'),('ZERO second settlement + order closure',counts['settlement_executions']==1 and counts['order_closures']==1,'1 / 1'),('ZERO second finalization + recognition + posting',counts['financial_finalizations']==1 and counts['profit_recognitions']==1 and counts['business_ledger_postings']==1,'1 / 1 / 1'),('ZERO second SOLD conversion + audit explainability',sold==1 and audit==1,'1 SOLD / VERIFIED audit'),('Persistent replay + restart reconstruction',replay==1 and h==1,'PASS / PASS')]; passed=sum(ok for _,ok,_ in checks)
  return {'checks':checks,'passed':passed,'posting':'POSTED' if p else 'BLOCKED','balance':'BALANCED' if b else 'BLOCKED','balanced_profit':None if not b else b['balanced_profit_minor'],'account':None if not b else b['ledger_account'],'inventory':'ZERO' if invmoves==0 else 'MUTATED','second_sale':'NO' if counts['sales']==1 else 'YES','second_financial':'NO' if counts['sales_financial_history']==1 else 'YES','second_settlement':'NO' if counts['settlement_executions']==1 else 'YES','second_closure':'NO' if counts['order_closures']==1 else 'YES','second_finalization':'NO' if counts['financial_finalizations']==1 else 'YES','second_recognition':'NO' if counts['profit_recognitions']==1 else 'YES','second_posting':'NO' if counts['business_ledger_postings']==1 else 'YES','second_sold':'NO' if sold==1 else 'YES','history':'APPEND-ONLY' if h==1 else 'BLOCKED','replay':'PASS' if replay==1 else 'FAIL','restart':'PASS' if replay==1 and h==1 else 'FAIL','result':'BUSINESS LEDGER BALANCE AUTHORITY VERIFIED' if passed==12 else 'BLOCKED'}
