from pathlib import Path
from services.m41b_acceptance_service import M41BAcceptanceService,BALANCE_ID
from services.business_performance_summary_service import BusinessPerformanceSummaryService
SUMMARY_ID='SUMMARY-M42A-001'; SUMMARY_REQUEST_ID='M42A-SUMMARY-REQUEST-001'
class M42AAcceptanceService:
 def __init__(self,path): self.path=Path(path); self.summary=BusinessPerformanceSummaryService(self.path)
 def execute(self):
  if M41BAcceptanceService(self.path).execute()['passed']!=12: raise RuntimeError('M41B BALANCED authority incomplete')
  k=dict(summary_id=SUMMARY_ID,balance_id=BALANCE_ID,summary_request_id=SUMMARY_REQUEST_ID,intent='SUMMARIZE'); self.summary.summarize(**k); self.summary.summarize(**k); self.summary=BusinessPerformanceSummaryService(self.path); self.summary.summarize(**k); return self.verify()
 def verify(self):
  with self.summary.database.read_connection() as c:
   s=c.execute('SELECT * FROM business_performance_summaries WHERE summary_id=?',(SUMMARY_ID,)).fetchone(); b=c.execute('SELECT * FROM business_ledger_balances WHERE balance_id=?',(BALANCE_ID,)).fetchone(); h=c.execute('SELECT COUNT(*) n FROM business_performance_summary_history WHERE summary_id=?',(SUMMARY_ID,)).fetchone()['n']; replay=c.execute("SELECT COUNT(*) n FROM replay_defense_history WHERE request_id=? AND attempted_event_type='BUSINESS_PERFORMANCE_SUMMARY'",(SUMMARY_REQUEST_ID,)).fetchone()['n']; counts={t:c.execute(f'SELECT COUNT(*) n FROM {t}').fetchone()['n'] for t in ('sales','sales_financial_history','settlement_executions','order_closures','financial_finalizations','profit_recognitions','business_ledger_postings','business_ledger_balances')}; sold=c.execute("SELECT COUNT(*) n FROM publication_lifecycle_events WHERE event_type='SOLD_CONVERSION'").fetchone()['n']; invmoves=0 if not s else c.execute('SELECT COUNT(*) n FROM inventory_history WHERE event_id=?',(s['summary_event_id'],)).fetchone()['n']; audit=0 if not s else c.execute("SELECT COUNT(*) n FROM audit_events WHERE event_id=? AND authority_type='BUSINESS_PERFORMANCE_SUMMARY' AND authority_id=? AND verification_result='VERIFIED'",(s['summary_event_id'],SUMMARY_ID)).fetchone()['n']; event=0 if not s else c.execute("SELECT COUNT(*) n FROM event_identity WHERE event_id=? AND event_type='BUSINESS_PERFORMANCE_SUMMARY'",(s['summary_event_id'],)).fetchone()['n']
  truth=bool(s and b and int(s['realized_profit_minor'])==int(b['balanced_profit_minor']) and int(s['revenue_minor'])==int(b['balanced_revenue_minor']) and int(s['cogs_minor'])==int(b['balanced_cogs_minor'])); checks=[('Accepted BALANCED ledger authority',bool(b and b['balance_result']=='BALANCED'),'BALANCED'),('Business performance truth reconstruction',truth,'revenue / COGS / realized profit match'),('Finalized sale count authority',bool(s and int(s['sale_count'])==1),'1 finalized sale'),('Explicit summary request + event identity',event==1,SUMMARY_REQUEST_ID),('Standalone performance summary execution',bool(s and s['summary_result']=='SUMMARIZED'),'SUMMARIZED'),('Exactly-once SUMMARIZED authority',h==1,'1 summary / 1 history'),('ZERO inventory mutation',invmoves==0,'ZERO'),('ZERO second sale + M24 financial event',counts['sales']==1 and counts['sales_financial_history']==1,'1 / 1'),('ZERO second settlement + order closure',counts['settlement_executions']==1 and counts['order_closures']==1,'1 / 1'),('ZERO second finalization + recognition + posting + balance',counts['financial_finalizations']==1 and counts['profit_recognitions']==1 and counts['business_ledger_postings']==1 and counts['business_ledger_balances']==1,'1 / 1 / 1 / 1'),('ZERO second SOLD conversion + audit explainability',sold==1 and audit==1,'1 SOLD / VERIFIED audit'),('Persistent replay + restart reconstruction',replay==1 and h==1,'PASS / PASS')]; passed=sum(ok for _,ok,_ in checks)
  return {'checks':checks,'passed':passed,'balance':'BALANCED' if b else 'BLOCKED','summary':'SUMMARIZED' if s else 'BLOCKED','sale_count':None if not s else s['sale_count'],'revenue':None if not s else s['revenue_minor'],'cogs':None if not s else s['cogs_minor'],'profit':None if not s else s['realized_profit_minor'],'account':None if not s else s['ledger_account'],'inventory':'ZERO' if invmoves==0 else 'MUTATED','second_sale':'NO' if counts['sales']==1 else 'YES','second_financial':'NO' if counts['sales_financial_history']==1 else 'YES','second_settlement':'NO' if counts['settlement_executions']==1 else 'YES','second_closure':'NO' if counts['order_closures']==1 else 'YES','second_finalization':'NO' if counts['financial_finalizations']==1 else 'YES','second_recognition':'NO' if counts['profit_recognitions']==1 else 'YES','second_posting':'NO' if counts['business_ledger_postings']==1 else 'YES','second_balance':'NO' if counts['business_ledger_balances']==1 else 'YES','second_sold':'NO' if sold==1 else 'YES','history':'APPEND-ONLY' if h==1 else 'BLOCKED','replay':'PASS' if replay==1 else 'FAIL','restart':'PASS' if replay==1 and h==1 else 'FAIL','result':'BUSINESS PERFORMANCE SUMMARY AUTHORITY VERIFIED' if passed==12 else 'BLOCKED'}
