from pathlib import Path
from services.m42a_acceptance_service import M42AAcceptanceService,SUMMARY_ID
from services.business_performance_intelligence_service import BusinessPerformanceIntelligenceService
INTELLIGENCE_ID='INTELLIGENCE-M43A-001'; INTELLIGENCE_REQUEST_ID='M43A-INTELLIGENCE-REQUEST-001'
class M43AAcceptanceService:
 def __init__(self,path): self.path=Path(path); self.intelligence=BusinessPerformanceIntelligenceService(self.path)
 def execute(self):
  if M42AAcceptanceService(self.path).execute()['passed']!=12: raise RuntimeError('M42A SUMMARIZED authority incomplete')
  k=dict(intelligence_id=INTELLIGENCE_ID,summary_id=SUMMARY_ID,intelligence_request_id=INTELLIGENCE_REQUEST_ID,intent='RECONSTRUCT_INTELLIGENCE'); self.intelligence.reconstruct(**k); self.intelligence.reconstruct(**k); self.intelligence=BusinessPerformanceIntelligenceService(self.path); self.intelligence.reconstruct(**k); return self.verify()
 def verify(self):
  with self.intelligence.database.read_connection() as c:
   i=c.execute('SELECT * FROM business_performance_intelligence WHERE intelligence_id=?',(INTELLIGENCE_ID,)).fetchone(); s=c.execute('SELECT * FROM business_performance_summaries WHERE summary_id=?',(SUMMARY_ID,)).fetchone(); h=c.execute('SELECT COUNT(*) n FROM business_performance_intelligence_history WHERE intelligence_id=?',(INTELLIGENCE_ID,)).fetchone()['n']; replay=c.execute("SELECT COUNT(*) n FROM replay_defense_history WHERE request_id=? AND attempted_event_type='BUSINESS_PERFORMANCE_INTELLIGENCE'",(INTELLIGENCE_REQUEST_ID,)).fetchone()['n']; tables=('sales','sales_financial_history','settlement_executions','order_closures','financial_finalizations','profit_recognitions','business_ledger_postings','business_ledger_balances','business_performance_summaries'); counts={t:c.execute(f'SELECT COUNT(*) n FROM {t}').fetchone()['n'] for t in tables}; sold=c.execute("SELECT COUNT(*) n FROM publication_lifecycle_events WHERE event_type='SOLD_CONVERSION'").fetchone()['n']; invmoves=0 if not i else c.execute('SELECT COUNT(*) n FROM inventory_history WHERE event_id=?',(i['intelligence_event_id'],)).fetchone()['n']; audit=0 if not i else c.execute("SELECT COUNT(*) n FROM audit_events WHERE event_id=? AND authority_type='BUSINESS_PERFORMANCE_INTELLIGENCE' AND authority_id=? AND verification_result='VERIFIED'",(i['intelligence_event_id'],INTELLIGENCE_ID)).fetchone()['n']; event=0 if not i else c.execute("SELECT COUNT(*) n FROM event_identity WHERE event_id=? AND event_type='BUSINESS_PERFORMANCE_INTELLIGENCE'",(i['intelligence_event_id'],)).fetchone()['n']
  truth=bool(i and s and int(i['sale_count'])==int(s['sale_count']) and int(i['revenue_minor'])==int(s['revenue_minor']) and int(i['realized_profit_minor'])==int(s['realized_profit_minor'])); metrics=bool(i and int(i['profit_margin_bps'])==8400 and int(i['average_revenue_minor'])==5000 and int(i['average_realized_profit_minor'])==4200 and i['performance_status']=='PROFITABLE'); checks=[('Accepted SUMMARIZED performance authority',bool(s and s['summary_result']=='SUMMARIZED'),'SUMMARIZED'),('Performance truth lineage reconstruction',truth,'summary → intelligence truth match'),('Decision metric derivation authority',metrics,'84.00% / 5000 / 4200 / PROFITABLE'),('Explicit intelligence request + event identity',event==1,INTELLIGENCE_REQUEST_ID),('Standalone performance intelligence execution',bool(i and i['intelligence_result']=='INTELLIGENCE_READY'),'INTELLIGENCE_READY'),('Exactly-once INTELLIGENCE_READY authority',h==1,'1 intelligence / 1 history'),('ZERO inventory mutation',invmoves==0,'ZERO'),('ZERO second sale + M24 financial event',counts['sales']==1 and counts['sales_financial_history']==1,'1 / 1'),('ZERO second settlement + order closure',counts['settlement_executions']==1 and counts['order_closures']==1,'1 / 1'),('ZERO second finalization + recognition + posting + balance + summary',counts['financial_finalizations']==1 and counts['profit_recognitions']==1 and counts['business_ledger_postings']==1 and counts['business_ledger_balances']==1 and counts['business_performance_summaries']==1,'1 / 1 / 1 / 1 / 1'),('ZERO second SOLD conversion + audit explainability',sold==1 and audit==1,'1 SOLD / VERIFIED audit'),('Persistent replay + restart reconstruction',replay==1 and h==1,'PASS / PASS')]; passed=sum(ok for _,ok,_ in checks)
  return {'checks':checks,'passed':passed,'summary':'SUMMARIZED' if s else 'BLOCKED','intelligence':'INTELLIGENCE_READY' if i else 'BLOCKED','margin':None if not i else i['profit_margin_bps'],'avg_revenue':None if not i else i['average_revenue_minor'],'avg_profit':None if not i else i['average_realized_profit_minor'],'status':None if not i else i['performance_status'],'inventory':'ZERO' if invmoves==0 else 'MUTATED','second_sale':'NO' if counts['sales']==1 else 'YES','second_financial':'NO' if counts['sales_financial_history']==1 else 'YES','second_settlement':'NO' if counts['settlement_executions']==1 else 'YES','second_closure':'NO' if counts['order_closures']==1 else 'YES','second_finalization':'NO' if counts['financial_finalizations']==1 else 'YES','second_recognition':'NO' if counts['profit_recognitions']==1 else 'YES','second_posting':'NO' if counts['business_ledger_postings']==1 else 'YES','second_balance':'NO' if counts['business_ledger_balances']==1 else 'YES','second_summary':'NO' if counts['business_performance_summaries']==1 else 'YES','second_sold':'NO' if sold==1 else 'YES','history':'APPEND-ONLY' if h==1 else 'BLOCKED','replay':'PASS' if replay==1 else 'FAIL','restart':'PASS' if replay==1 and h==1 else 'FAIL','result':'BUSINESS PERFORMANCE INTELLIGENCE AUTHORITY VERIFIED' if passed==12 else 'BLOCKED'}
