from pathlib import Path
from services.m43a_acceptance_service import M43AAcceptanceService,INTELLIGENCE_ID
from services.business_decision_service import BusinessDecisionService
DECISION_ID='DECISION-M44A-001'; DECISION_REQUEST_ID='M44A-DECISION-REQUEST-001'
class M44AAcceptanceService:
 def __init__(self,path): self.path=Path(path); self.decision=BusinessDecisionService(self.path)
 def execute(self):
  if M43AAcceptanceService(self.path).execute()['passed']!=12: raise RuntimeError('M43A INTELLIGENCE_READY authority incomplete')
  k=dict(decision_id=DECISION_ID,intelligence_id=INTELLIGENCE_ID,decision_request_id=DECISION_REQUEST_ID,intent='RECONSTRUCT_DECISION'); self.decision.reconstruct(**k); self.decision.reconstruct(**k); self.decision=BusinessDecisionService(self.path); self.decision.reconstruct(**k); return self.verify()
 def verify(self):
  with self.decision.database.read_connection() as c:
   d=c.execute('SELECT * FROM business_decisions WHERE decision_id=?',(DECISION_ID,)).fetchone(); i=c.execute('SELECT * FROM business_performance_intelligence WHERE intelligence_id=?',(INTELLIGENCE_ID,)).fetchone(); h=c.execute('SELECT COUNT(*) n FROM business_decision_history WHERE decision_id=?',(DECISION_ID,)).fetchone()['n']; replay=c.execute("SELECT COUNT(*) n FROM replay_defense_history WHERE request_id=? AND attempted_event_type='BUSINESS_DECISION'",(DECISION_REQUEST_ID,)).fetchone()['n']; tables=('sales','sales_financial_history','settlement_executions','order_closures','financial_finalizations','profit_recognitions','business_ledger_postings','business_ledger_balances','business_performance_summaries','business_performance_intelligence'); counts={t:c.execute(f'SELECT COUNT(*) n FROM {t}').fetchone()['n'] for t in tables}; sold=c.execute("SELECT COUNT(*) n FROM publication_lifecycle_events WHERE event_type='SOLD_CONVERSION'").fetchone()['n']; invmoves=0 if not d else c.execute('SELECT COUNT(*) n FROM inventory_history WHERE event_id=?',(d['decision_event_id'],)).fetchone()['n']; audit=0 if not d else c.execute("SELECT COUNT(*) n FROM audit_events WHERE event_id=? AND authority_type='BUSINESS_DECISION' AND authority_id=? AND verification_result='VERIFIED'",(d['decision_event_id'],DECISION_ID)).fetchone()['n']; event=0 if not d else c.execute("SELECT COUNT(*) n FROM event_identity WHERE event_id=? AND event_type='BUSINESS_DECISION'",(d['decision_event_id'],)).fetchone()['n']
  lineage=bool(d and i and i['intelligence_result']=='INTELLIGENCE_READY' and d['intelligence_id']==i['intelligence_id']); deterministic=bool(d and d['decision_code']=='SCALE_PROFITABLE_CHANNEL' and '50.00%' in d['decision_reason']); checks=[('Accepted INTELLIGENCE_READY authority',bool(i and i['intelligence_result']=='INTELLIGENCE_READY'),'INTELLIGENCE_READY'),('Decision lineage reconstruction',lineage,'intelligence → decision truth match'),('Deterministic decision derivation authority',deterministic,'SCALE_PROFITABLE_CHANNEL'),('Explicit decision request + event identity',event==1,DECISION_REQUEST_ID),('Standalone business decision execution',bool(d and d['decision_result']=='DECISION_READY'),'DECISION_READY'),('Exactly-once DECISION_READY authority',h==1,'1 decision / 1 history'),('ZERO inventory mutation',invmoves==0,'ZERO'),('ZERO second sale + M24 financial event',counts['sales']==1 and counts['sales_financial_history']==1,'1 / 1'),('ZERO second settlement + order closure',counts['settlement_executions']==1 and counts['order_closures']==1,'1 / 1'),('ZERO second finalization + recognition + posting + balance + summary + intelligence',all(counts[t]==1 for t in tables[4:]),'1 / 1 / 1 / 1 / 1 / 1'),('ZERO second SOLD conversion + audit explainability',sold==1 and audit==1,'1 SOLD / VERIFIED audit'),('Persistent replay + restart reconstruction',replay==1 and h==1,'PASS / PASS')]; passed=sum(ok for _,ok,_ in checks)
  return {'checks':checks,'passed':passed,'intelligence':'INTELLIGENCE_READY' if i else 'BLOCKED','decision':'DECISION_READY' if d else 'BLOCKED','decision_code':None if not d else d['decision_code'],'reason':None if not d else d['decision_reason'],'inventory':'ZERO' if invmoves==0 else 'MUTATED','second_sale':'NO' if counts['sales']==1 else 'YES','second_financial':'NO' if counts['sales_financial_history']==1 else 'YES','second_settlement':'NO' if counts['settlement_executions']==1 else 'YES','second_closure':'NO' if counts['order_closures']==1 else 'YES','second_finalization':'NO' if counts['financial_finalizations']==1 else 'YES','second_recognition':'NO' if counts['profit_recognitions']==1 else 'YES','second_posting':'NO' if counts['business_ledger_postings']==1 else 'YES','second_balance':'NO' if counts['business_ledger_balances']==1 else 'YES','second_summary':'NO' if counts['business_performance_summaries']==1 else 'YES','second_intelligence':'NO' if counts['business_performance_intelligence']==1 else 'YES','second_sold':'NO' if sold==1 else 'YES','history':'APPEND-ONLY' if h==1 else 'BLOCKED','replay':'PASS' if replay==1 else 'FAIL','restart':'PASS' if replay==1 and h==1 else 'FAIL','result':'BUSINESS DECISION AUTHORITY VERIFIED' if passed==12 else 'BLOCKED'}
