from pathlib import Path
from services.m44a_acceptance_service import M44AAcceptanceService,DECISION_ID
from services.operating_command_chain_service import OperatingCommandChainService,STAGES

CHAIN=(
 ('ACTION_PLAN','ACTION-PLAN-M45A-001',DECISION_ID,'M45A-ACTION-PLAN-REQUEST-001','ACTION_PLAN_READY','EXPAND_PROFITABLE_CHANNEL'),
 ('BUSINESS_PRIORITY','PRIORITY-M46A-001','ACTION-PLAN-M45A-001','M46A-PRIORITY-REQUEST-001','PRIORITIZED','PRIORITY_1_PROFITABLE_CHANNEL'),
 ('EXECUTION_QUEUE','EXECUTION-QUEUE-M47A-001','PRIORITY-M46A-001','M47A-EXECUTION-QUEUE-REQUEST-001','EXECUTION_READY','QUEUE_PROFITABLE_CHANNEL_EXPANSION'),
 ('OPERATING_COMMAND','COMMAND-M48A-001','EXECUTION-QUEUE-M47A-001','M48A-COMMAND-REQUEST-001','COMMAND_READY','EXECUTE_CONTROLLED_CHANNEL_EXPANSION'),
 ('BUSINESS_OPERATING_STATE','OPERATING-STATE-M49A-001','COMMAND-M48A-001','M49A-OPERATING-STATE-REQUEST-001','OPERATING_READY','OPERATE_CONTROLLED_GROWTH'),
)
class M45M49AcceptanceService:
 def __init__(self,path): self.path=Path(path); self.chain=OperatingCommandChainService(self.path)
 def execute(self):
  if M44AAcceptanceService(self.path).execute()['passed']!=12: raise RuntimeError('M44A DECISION_READY authority incomplete')
  for stage,aid,pid,rid,_,_ in CHAIN:
   k=dict(stage=stage,authority_id=aid,parent_id=pid,request_id=rid,intent=f'RECONSTRUCT_{stage}'); self.chain.reconstruct(**k); self.chain.reconstruct(**k); self.chain=OperatingCommandChainService(self.path); self.chain.reconstruct(**k)
  return self.verify()
 def verify(self):
  checks=[]
  with self.chain.database.read_connection() as c:
   previous=('business_decisions','decision_id','decision_result',DECISION_ID,'DECISION_READY')
   for stage,aid,pid,rid,expected,code in CHAIN:
    spec=next(x for x in STAGES if x[0]==stage); table,idcol,parentcol,result=spec[5],spec[6],spec[7],spec[8]; resultcol=self.chain._result_col(table); eventcol=self.chain._event_col(table); requestcol=self.chain._request_col(table); row=c.execute(f'SELECT * FROM {table} WHERE {idcol}=?',(aid,)).fetchone(); parent=c.execute(f'SELECT * FROM {previous[0]} WHERE {previous[1]}=? AND {previous[2]}=?',(previous[3],previous[4])).fetchone(); hist=c.execute(f'SELECT COUNT(*) n FROM {table}_history WHERE {idcol}=?',(aid,)).fetchone()['n']; replay=c.execute('SELECT COUNT(*) n FROM replay_defense_history WHERE request_id=? AND attempted_event_type=?',(rid,stage)).fetchone()['n']; audit=0 if not row else c.execute('SELECT COUNT(*) n FROM audit_events WHERE event_id=? AND authority_type=? AND authority_id=? AND verification_result=?',(row[eventcol],stage,aid,'VERIFIED')).fetchone()['n']; event=0 if not row else c.execute('SELECT COUNT(*) n FROM event_identity WHERE event_id=? AND event_type=?',(row[eventcol],stage)).fetchone()['n']; ok=bool(parent and row and row[parentcol]==pid and row[resultcol]==expected and row['authority_code']==code and row[requestcol]==rid and hist==1 and replay==1 and audit==1 and event==1); checks.append((f'{stage} authority reconstruction',ok,f'{previous[4]} → {expected} / {code}')); previous=(table,idcol,resultcol,aid,expected)
   preserved=('sales','sales_financial_history','settlement_executions','order_closures','financial_finalizations','profit_recognitions','business_ledger_postings','business_ledger_balances','business_performance_summaries','business_performance_intelligence','business_decisions'); counts={t:c.execute(f'SELECT COUNT(*) n FROM {t}').fetchone()['n'] for t in preserved}; sold=c.execute("SELECT COUNT(*) n FROM publication_lifecycle_events WHERE event_type='SOLD_CONVERSION'").fetchone()['n']; inv=sum(c.execute(f'SELECT COUNT(*) n FROM inventory_history WHERE event_id IN (SELECT {self.chain._event_col(x[5])} FROM {x[5]})').fetchone()['n'] for x in STAGES)
   checks += [('Full M45-M49 lineage continuity',all(ok for _,ok,_ in checks),'DECISION_READY → ACTION_PLAN_READY → PRIORITIZED → EXECUTION_READY → COMMAND_READY → OPERATING_READY'),('ZERO inventory mutation',inv==0,'ZERO'),('ZERO second sale + M24 financial',counts['sales']==1 and counts['sales_financial_history']==1,'1 / 1'),('ZERO second settlement + closure',counts['settlement_executions']==1 and counts['order_closures']==1,'1 / 1'),('ZERO second finalization + recognition',counts['financial_finalizations']==1 and counts['profit_recognitions']==1,'1 / 1'),('ZERO second posting + balance',counts['business_ledger_postings']==1 and counts['business_ledger_balances']==1,'1 / 1'),('ZERO second summary + intelligence + decision',counts['business_performance_summaries']==1 and counts['business_performance_intelligence']==1 and counts['business_decisions']==1,'1 / 1 / 1'),('ZERO second SOLD conversion',sold==1,'1 SOLD'),('Exactly-once action plan',c.execute('SELECT COUNT(*) n FROM action_plans').fetchone()['n']==1,'1'),('Exactly-once priority',c.execute('SELECT COUNT(*) n FROM business_priorities').fetchone()['n']==1,'1'),('Exactly-once execution queue',c.execute('SELECT COUNT(*) n FROM execution_queues').fetchone()['n']==1,'1'),('Exactly-once operating command',c.execute('SELECT COUNT(*) n FROM operating_commands').fetchone()['n']==1,'1'),('Exactly-once operating state',c.execute('SELECT COUNT(*) n FROM business_operating_states').fetchone()['n']==1,'1'),('Append-only authority history',all(c.execute(f'SELECT COUNT(*) n FROM {x[5]}_history').fetchone()['n']==1 for x in STAGES),'1 / 1 / 1 / 1 / 1'),('Persistent replay defense',all(c.execute('SELECT COUNT(*) n FROM replay_defense_history WHERE request_id=? AND attempted_event_type=?',(rid,stage)).fetchone()['n']==1 for stage,_,_,rid,_,_ in CHAIN),'PASS'),('Restart reconstruction',all(c.execute(f'SELECT COUNT(*) n FROM {x[5]}').fetchone()['n']==1 for x in STAGES),'PASS')]
  passed=sum(ok for _,ok,_ in checks); state=self.chain.get('BUSINESS_OPERATING_STATE','OPERATING-STATE-M49A-001') if passed else None
  return {'checks':checks,'passed':passed,'operating_state':'BLOCKED' if not state else state['operating_state_result'],'operating_code':None if not state else state['authority_code'],'inventory':'ZERO' if inv==0 else 'MUTATED','history':'APPEND-ONLY' if checks[-3][1] else 'BLOCKED','replay':'PASS' if checks[-2][1] else 'FAIL','restart':'PASS' if checks[-1][1] else 'FAIL','result':'M45-M49 OPERATING COMMAND CHAIN VERIFIED' if passed==20 else 'BLOCKED'}
